apiVersion: v1
kind: Pod
metadata:
  namespace: k8s-guide
  name: pod-define
  labels:
    app: pod-define
    environment: dev
  annotations:
    name: string
spec:
  restartPolicy: "Always|Never|OnFailure"
  nodeSelector:
    speed: fast
  imagePullSecrets:
    - name: value
  hostNetwork: false
  volumes:
    - name: localvol
      emptyDir: {}
    - name: hostvol
      hostPath:
        path: /data
    - name: nsfvol
      nfs:
        path: ip
        server: /data
    - name: pvcvol
      persistentVolumeClaim:
        claimName: myclaim
    - name: secretvol
      secret:
        secretName: "xxx"
    - name: configMapvol
      configMap:
        - name: xxx

  containers:
    - name: pod-define
      image: tomcat
      imagePullPolicy: "Always|Never|IfNotPresent"
      command: ["sh", "-c", "tail -f /logs/catalina*.log"]
      args:
        - "a=b"
      workingDir: /tmp
      volumeMounts:
        - mountPath: /data
          name: localvol
          readOnly: false
      ports:
        - containerPort: 8080
          hostPort: 9090
          protocol: "TCP|UDP"
          name: web-port
      env:
        - name: MYSQL_HOST
          value: 127.0.0.1
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 5m
          memory: 8Mi
      livenessProbe:
        exec:
          command:
            - "echo live"
        httpGet:
          port: 8080
          host: current
          path: /actuator/health
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 2
        failureThreshold: 2
      readinessProbe:
        exec:
          command:
            - "echo ready"
        httpGet:
          port: 8080
          host: current
          path: /actuator/readiness
        initialDelaySeconds: 3
        timeoutSeconds: 3
        periodSeconds: 10
        successThreshold: 2
        failureThreshold: 2
      securityContext:
        privileged: false



