apiVersion: v1
kind: ReplicationController
metadata:
  namespace: k8s-guide
  name: mysql
spec:
  replicas: 2
  selector:
    app: mysql
  template:
    metadata:
      # pod meta
    spec:
      # pod spec

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-guide
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
    # pod meta
    spec:
    # pod spec

---

