apiVersion: v1
kind: Service
metadata:
  namespace: k8s-guide
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  namespace: k8s-guide
  name: myweb
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
    - port: 30001
      #nodePort: 30001
      targetPort: 8080
      name: service-port
    - port: 8005
      name: shutdown-port
  selector:
    app: myweb
