---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-guide-dev

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: k8s-guide-dev
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
