apiVersion: v1
kind: Pod
metadata:
  namespace: k8s-guide
  name: myweb
  labels:
    app: myweb
spec:
  volumes:
    - name: localvol
      emptyDir: {}
    - name: hostvol
      hostPath:
        path: /data
    - name: nsfvol
      nfs:
        path: ip
        server: /data
    - name: pvcvol
      persistentVolumeClaim:
        claimName: myclaim
  containers:
  - name: myweb
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    volumeMounts:
      - mountPath: /mydata
        name: localvol
    env:
    - name: MYSQL_SERVICE_HOST
      value: 'mysql'
    - name: MYSQL_SERVICE_PORT
      value: '3306'
